json.id ingredient.id
json.name ingredient.name
json.picture ingredient.picture
json.calories ingredient.calories
json.fat ingredient.fat
json.sodium ingredient.sodium
json.carbs ingredient.carbs
json.protein ingredient.protein
json.sugar ingredient.sugar
json.cholesterol ingredient.cholesterol
json.user_id ingredient.user_id
